const types = {
  INCREAMENT: {
    BREAK: "BREAK_INCREAMENT",
    SESSION: "SESSION_INCREAMENT"
  },
  DECREAMENT: {
    BREAK: "BREAK_DECREAMENT",
    SESSION: "SESSION_DECREAMENT"
  },
  RESET: "RESET"
}

export default types;